# Generated by Django 4.2.7 on 2023-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slang", models.SlugField()),
                ("original_link", models.URLField()),
                ("access_counter", models.IntegerField()),
            ],
        ),
    ]
