# Generated by Django 4.2.7 on 2023-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortener",
            name="access_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shortener",
            name="slang",
            field=models.SlugField(default="qatqycwqsb"),
        ),
    ]
